### ISSUE TITLE
Triple-backquote isn't highlighted with the same color as single-backquote

### ISSUE THREAD

**Issue by cblp** [burodepeper/language-markdown#100]
![_002](https://cloud.githubusercontent.com/assets/63495/14079900/5c1cb722-f512-11e5-9b7a-33aac5995903.png)

**Comment by burodepeper** [comment]
Hi @cblp,
Thanks for reporting this. My main guideline for implementation is the CommonMark Spec, which has [the following rules for code spans](http://spec.commonmark.org/0.22/#code-spans). The triple backtick is indeed valid, and I'm not sure why I haven't implemented it as such. I'll have a closer look at it. Unless I've had a good reason not to implement it (possibly because of nested code spans) it shouldn't be a problem to add this.

**Comment by burodepeper** [comment]
Fixed. Will be part of the next update.
