### ISSUE TITLE
Deal with bold + italic when using only asterisks

### ISSUE THREAD

**Issue by andya9** [burodepeper/language-markdown#104]
When I use ```*__bold-italic__*``` everything is fine (the word gets both bold and italic styling), whereas if I use ```***bold-italic***``` I only get bold styling.

**Comment by burodepeper** [comment]
Hi @andya9,

Thanks for reporting this. I'm afraid this is going to be labeled as a `probably not going to fix this`, but that's mostly because of a personal preference. There are two conflicting concepts here, and your issue is pretty much where they overlap.

1) I believe it's better to think of the semantical terms _emphasis_ and _strong emphasis_ instead of _italic_ and _bold_. Whatever (strong) emphasis will look like in a rendered document is up to a stylesheet, and shouldn't be of issue when you're writing something. I acknowledge that over time the consensus has become that emphasis equals italics, and strong emphasis equals bold text.

2) The other thing has to do with nesting different types of inline styles. Because there is no set standard (well, there's is something, but that is awfully confusing), things can get a little tricky in both understanding it from the user-point-of-view and parsing it. My personal preference is to choose an option, and go with it, and to avoid overcomplicating things. Currently, the choice is that `_` represents emphasis, and `**` represents strong emphasis. This will probably become optional sometime in the future, but that is what it is right now. The actually parser is a bit more lenient actually. I've chosen this approach based also on the convention set by applications such as iA Writer and Ulysses.

This subject is rather subjective, and I'm open for ideas if you got good ones. Another major deciding factor for keeping this as simple as possible (take a look at the [commonmark specs](http://spec.commonmark.org/0.22/#emphasis-and-strong-emphasis) on this to get an idea of what I'm talking about) is that the way grammar can be parsed in Atom is limited, and I'm trying to make the best of what's possible. There's a good chance that I'm going to take another look at how emphasis is implemented in the foreseeable future, so now would be a good time if you have any ideas on the subject.

**Comment by andya9** [comment]
Sadly no real solutions. Actually I don’t like the ```***``` syntax either; I thought about using it because of consistency: I too think in terms of emphasis/strong emphasis, so I thought something like "if one asterisk is emphasis, then two asterisks are strong emphasis". 
But if it is difficult to parse, maybe I should just choose practicality over consistency and use ```**``` vs ```_```, as you say.

**Comment by burodepeper** [comment]
There's a new release coming up which adds keybindings for adding emphasis, see #103. How about that? ; )

**Comment by andya9** [comment]
I like it! but won’t it create problems if you don’t add a ctrl or shift to activate it?

**Comment by andya9** [comment]
No, nevermind: if it works on selected text only there’s no problem

**Comment by burodepeper** [comment]
Not really. Atom already wraps selected text in brackets for instance, and it works in the same way. I haven't released it yet, because I'm letting my subconscious think it through some more, but yeah, as you say, it only works on selected text. Feels quite natural.

**Comment by andya9** [comment]
I’m closing this even if not really solved, because your solution is probably the best one.

**Comment by burodepeper** [comment]
Thanks! If you any other good ideas, don't hesitate to throw them my way!
