### ISSUE TITLE
Unable to use asterisk

### ISSUE THREAD

**Issue by MGallow** [burodepeper/language-markdown#108]
I'm no longer able to use an asterisk with the package enabled. I suspect there's a conflict with the added shortcuts. I'm on version 0.13.0. Atom 1.7.3.

**Comment by burodepeper** [comment]
Hi @MGallow, thanks for reporting.

I have indeed attached an event to the asterisk (see #103), but it should only do anything when there's also text selected. This behaviour can be disabled via the settings, although it shouldn't be necessary. I have a hypothesis (see #72) the Atom needs to restarted after an update to a package that adds an extra setting; otherwise it causes weird bugs like this.

Have you tried reloading Atom? If so, did it work? If it didn't, does disabling the option via the `language-markdown` settings work? If that also doesn't work, perhaps it's an OS-related issue, or perhaps a conflict with another package. If so, could you supply me with some additional information...

**Comment by MGallow** [comment]
Ah, yes reloading Atom resolved the issue. Everything appears to be working correctly now. Thanks, love the package!

**Comment by burodepeper** [comment]
Good to know, and you're welcome!
