### ISSUE TITLE
Marginfigure OR embedded latex breaking rmarkdown

### ISSUE THREAD

**Issue by jtth** [burodepeper/language-markdown#109]
If I put the following into a document it stops parsing syntax below the block.

```
 ```{marginfigure}
![](/Users/jtth/Dropbox/Proposal/text/draft1/gabor.png)
A Gabor patch. These Gabor patches are described by $g(x,y;\lambda,\theta,\psi,\sigma,\gamma) = \exp\left(-\frac{x'^2+\gamma^2y'^2}{2\sigma^2}\right)\sin\left(2\pi\frac{x'}{\lambda}+\psi\right)$, where $\lambda$ ranges from .01 to .1, $\theta$ ranges from 0 to 90, $\psi = 0, \sigma = 50, \gamma = 1$. Degrees of rotation corresponds with the value of $\theta$ and the spacing between the stripes corresponds with $\lambda$.
 ```
```

It ends with three '`' too.

**Comment by burodepeper** [comment]
Thanks for reporting, I'll have a look at it!

**Comment by burodepeper** [comment]
@jtth I've taken a quick look, and I've found two things.

1. The syntax you used `{marginfigure}` isn't supported (by this package at least), so I've assumed `{r engine='marginfigure'}`. That at least starts parsing the fenced-code-block, which leads me to:
2. There's a lot of tokens on that single line, and due to performance issues, the amount of tokens is limited by Atom to a hundred. I've tried increasing this via the grammar, but it appears to be immutable. This may be the cause that it sort of stops parsing that line, and for some reason doesn't exit the scope it's in at that moment, etc, etc.

What additional, relevant packages do you have installed?

**Comment by jtth** [comment]
Linter, language-r, r-exec, and tidy-markdown. 

Interestingly, replacing `marginfigure` (used with the tufte-template in Rmarkdown) with your version and replacing the quotes with `\prime` seems to work. And that is probably better. Thanks for the heads-up; I was taking pandoc's ability to interpret quote characters and transferring that to the text editor. Some day, maybe.

**Comment by burodepeper** [comment]
> Quotes are bitches. [@burodepeper2016]

May we consider this issue closed then?

**Comment by jtth** [comment]
Indeed. Thanks!
