### ISSUE TITLE
syntax highlighting error in inline links w/o separation 

### ISSUE THREAD

**Issue by tsaiid** [burodepeper/language-markdown#117]
Atom Version: 1.8.0
System: Mac OS X 10.11.4
language-markdown package, v0.14.0
Theme: Atom material

When using inline links without separations, the syntax does not highlighted correctly.
This does not happen in reference-style links.

Test text: 

```md
[abc](https://uccu.cool3c.com/)and[cde](https://uccu.cool3c.com/)

[abc][1]and[cde][1]

[1]: https://uccu.cool3c.com/
```

it shows: 

![2016-06-09 1 54 31](https://cloud.githubusercontent.com/assets/4302689/15920075/bc0f8c5c-2e49-11e6-8468-750eda5224bf.png)

**Comment by burodepeper** [comment]
Thanks for reporting, I'll have a look at it.

**Comment by burodepeper** [comment]
Fixed by disallowing parenthesis in the link-destination element. I believe theoretically something such as `[link]((a)and(b))` is valid according to CommonMark (Github parses it as a relative link to `(a)and(b)` for instance), but I think your use-case is more realistic at the moment. Perhaps I'll fix it properly in the future.

![schermafbeelding 2016-06-13 om 13 11 47](https://cloud.githubusercontent.com/assets/3703530/16005677/d57530b2-3168-11e6-8ab7-b4a0dacd5416.png)
