### ISSUE TITLE
Incompatibility with other extensions

### ISSUE THREAD

**Issue by humanfactors** [burodepeper/language-markdown#120]
I'm unsure if this is an issue which can be resolved. However, the other major extensions for markdown (BibTeX autocomplete, autocomplete-plus, and nvatom) do not seem to detect the language "Markdown" as suitable. It's quite frustrating as I am unsure of where all these extensions have compatibility issues, but it appear they are all based off the original gfm package.

Are you able to integrate a method such that other extensions which depend on `launguage-gfm` simply revert to your package? Or do those extensions need to change to you? It's pretty game changing for me, because I would rather have nvatom, BibTeX autocomplete, and simpler language detection in exchange for slightly less glossy highlighting.

**Comment by burodepeper** [comment]
I think those packages need a small change. Documents are either detected by their extension or a base grammar scope. I've changed the latter from `source.gfm` to `text.md` and it's possible that those packages tie in to it. I think that's why it might not work. If you could link all affected packages here (preferably a link to the repo), I'll have a look.

**Comment by humanfactors** [comment]
Cheers for having a look much appreciated.

1. The [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) actually does appear to work with your package on my Linux machine. Not sure why I was getting the errors on Windows.

2. [nvatom](https://github.com/seongjaelee/nvatom) actually functions with Markdown, if you modify the `interlink.coffee` and change the `        editor.setGrammar(atom.grammars.grammarForScopeName('source.gfm.nvatom'))` line to text.md, and then change `loadGrammarSync` method to specify language-markdown package. However, a side effect is that this will break the interlink capabilities. Interlink is basically a way to make markup styled as `[[foo]]` to link to a note called `foo.md`. The specifications for interlink seem quite embedded in gfm.

I had an attempt at compiling the interlink grammar into the language-markdown package, but I'm not experienced enough to actually get it to work. Gist [nvatom.cson](https://gist.github.com/humanfactors/b13e42cf9e25b51dadf313e409799228) was my futile attempt. I assumed I had to modify and .ass.

_3. Not really important, but it would be nice if the [pandoc flavoured markdown package](https://github.com/leipert/language-pfm) could somehow be integrated too. However, I haven't had any compability issues_

Thanks again for your time, it makes a huge difference to my workflow :)

**Comment by burodepeper** [comment]
Thanks.

I'll double-check `autocomplete-bibtex` myself. Adding the interlinks shouldn't be an issue, kudos for the gist. Do you know if the interlink syntax comes from some standardized specifications? I've never seen it before. _The `.ass` thing is only for tests btw. This package compiles its grammar file, unlike literally all other packages, so that's probably why you didn't get it to work._

Pandoc is on the todo-list for the future. I've been adding a few features here and there, but haven't had time yet to fully look in to it. One day!!

@seongjaelee See the comment above. Your package `nvatom` is tied into the `language-gfm` package. Can you think of an easy way so our packages play along nicely?

**Comment by humanfactors** [comment]
The actual interlink function appears to be unique to the nvatom package. However, the actual syntax seems to be derrived from Example 511 on the spec.commonmark.org. Sorry I can't be much more help!

**Comment by burodepeper** [comment]
No problem, thanks. I haven't gotten around to proper nested brackets yet, but I'll add a quick fix just for the interlinks.

**Comment by burodepeper** [comment]
I've looked into this issue today, and there's no easy fix. `nvatom` is build around `language-gfm`, and while changing the former to work around `language-markdown` shouldn't be that difficult, supporting both packages will require more effort. Perhaps the best course of action would be to report this as an issue over at `nvatom`, and let @seongjaelee decide if and how to implement this. I won't mind helping out though.

**Comment by humanfactors** [comment]
Thanks heaps for your time regardless. I've raised it as an issue and may fork it myself at some point. I managed to do a hacky work around for my local machine but it's not a suitable fix for public release. Cheers.

**Comment by burodepeper** [comment]
Good luck! Let me know if I can help.
