### ISSUE TITLE
Fenced-code-blocks with unrecognized languages are not closed properly

### ISSUE THREAD

**Issue by heavywatal** [burodepeper/language-markdown#121]
The main problem of #112 seems to be left unfixed. (But thank you for re-adding R to the supported languages!)

```
'''nohighlight
first block
'''

*dead, non-italic*
we are still in a `fenced.code.md`, `ctrl-cmd-p` says.

'''nohighlight
second block
''' (here the first block seems to be closed)

*resurrection! italic*
```

**Comment by burodepeper** [comment]
I know, and I will have another look at it when I have some time on my hands. The issue is that the current structure of the grammar doesn't allow for easy addition of a generic code block, because it doesn't match with any specific languages afterwards. Adding additional languages is an easy fix for the time being.

**Comment by burodepeper** [comment]
I've added support for generic fenced-code-blocks. Update is on its way. Let me know if this finally solves your issues.

![schermafbeelding 2016-07-09 om 13 13 07](https://cloud.githubusercontent.com/assets/3703530/16707675/402706ba-45d7-11e6-89b4-8b2749b238aa.png)

**Comment by heavywatal** [comment]
Great!! I have installed 0.15.0 and confirmed that it works perfectly. Thanks a lot!

**Comment by burodepeper** [comment]
You're welcome!
