### ISSUE TITLE
Setting Code block background color for full line height

### ISSUE THREAD

**Issue by rkpatel33** [burodepeper/language-markdown#132]
I am trying to highlight code blocks in a slightly background color than the primary editor background, but when I use this code in my personal stylesheeet, I get the following result (using an exaggerated color to make the issue stand out). Notice the dark spaces between lines bc it seems I am not selecting the right element to cover the whole like all the day across.

Is there another selector I can use to cover the whole background behind code blocks?

I am trying to tweak my markdown highlighting setting with the ultimate goal of creating a full markdown theme (which will be my first) based on extended language-markdown classes.

```
atom-text-editor::shadow {
    .code.fenced {
        background-color: #2f495b;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/3799489/18299999/4bf174ae-7493-11e6-8785-1125c75079a3.png)

**Comment by burodepeper** [comment]
I'm afraid I can't help you here. I've ran into the same issue with `minimal-syntax`. The code tokens in Atom are all individually `<span>` elements styled as `inline-block` and there is no containing element.

Actually, I think I might help. For this to work, the `<div class='line'>` element needs an extra class. This would have to happen on the package level. I've never looked at the APIs needed for this, but I suppose it is technically possible. I'll leave this issue open until I've had at least some time to look at it. And feel free to try it yourself, and submit it as a PR. Seems like a useful feature.

**Comment by rkpatel33** [comment]
That was my thought as well. I figure if the language-markdown package can
add its own tags anywhere inside the shadow dom, it should be able to add a
tag to those line elements. Maybe something like `class = “line
code-block”`.

I am just getting going with hacking Atom, so I’m just not sure how
grammars, packages, UI themes all fit and work together, but seems like it
should be very doable.

I am going to read the Atom flight manual back to front later this week so
I might have a better idea then. Will post you if I figure it out.



_________________________
Rishi Patel | mail@rishinyc.com

**Comment by burodepeper** [comment]
It works a little different than that though. A grammar doesn't interact with the line directly, it only interacts with the content of that line. For this idea to work, it would have to scan all lines in a document after every mutation, and add a class to a line when it detects something embedded (in the sense that it could apply to more than just code blocks in Markdown).

We can try getting this to work in a `dev` branch over here, but it could be interesting in the long run to move this to a separate package, because I'm sure it could be interesting for other languages.

**Comment by rkpatel33** [comment]
​Some ​of the markdown preview packages do realtime updates, I wonder if
anything in there is useful. I’ve take a quick look but need to understand
the Atom api better.


_________________________
Rishi Patel | mail@rishinyc.com

On Wed, Sep 7, 2016 at 12:29 PM, David van Gemeren <notifications@github.com

**Comment by burodepeper** [comment]
The pseudocode would be something like:

```
if (buffer.changes())
  lines = currentEditor.getLines()
  for line in lines
    if line.getScopes().contains("code-block")
      line.addClass("code-block")
    else
      line.removeClass("code-block")
```

So, it's not that difficult, but with Atom it's always a challenge to find the right APIs. I've got some 'real' work that has priority at the moment, but with a bit of luck, I can assemble a first version this weekend. Would be nice to get this working.

**Comment by burodepeper** [comment]
![schermafbeelding 2016-09-11 om 12 02 19](https://cloud.githubusercontent.com/assets/3703530/18416553/e88c70ca-7817-11e6-97a7-db4f852ca883.png)

_Tada_, I got it working, I guess. Try the `dev-132` branch if you want to see it for yourself.

There's one remaining issue though. This code uses `DisplayMarkers` and `Decorations` to mark the ranges that contain code-blocks. I believe that's the way Atom wants you to do things like this. They are also used for cursors, current-line, selections, etc. A DisplayMarker marks a range in the current buffer, and you attach a Decoration to it for visualization. However, the markers are re-created on every change to the buffer at the moment. There's a mechanism to automatically invalidate a marker when its content changes in the buffer, however that's not the case here, or I am using it wrong.

A possible, "stupid" solution would be to simply flush all existing markers at the start of every cycle. A [DisplayMarkerLayer](https://atom.io/docs/api/v1.10.2/DisplayMarkerLayer) seems the perfect candidate for this, but the downside is that it's marked as **Experimental**. Cycling through _all_ decorations and only clearing the ones marked `embedded-code` is also an option.

Any ideas for possibly a smarter solution?

**Comment by rkpatel33** [comment]
David, sorry for the delayed response, I have a been traveling (and still
am actually).

I am not familiar with running branches in Atom. How do I do that for a
package that I already have installed like this situation?


_________________________
Rishi Patel | mail@rishinyc.com

On Sun, Sep 11, 2016 at 6:14 AM, David van Gemeren <notifications@github.com

**Comment by burodepeper** [comment]
Don't worry about it!

Okay, I hope I'm not forgetting any steps, but the general idea is to get clone a local copy of `language-markdown`, link it to the dev-mode of Atom, and then switch to the `dev-132` branch. I'm also assuming you have Node.js installed.

1. Clone the `language-markdown` repo to your local machine.
2. Open Terminal and navigate to the directory where you cloned `language-markdown`.
3. Enter `npm install --save-dev` to install the dependencies, maybe a `sudo` is needed, not sure. (Atom does this automatically for any packages you install)
4. Enter `apm link -d`. This basically tells Atom to use this version of the package (and not the one installed via Atom) when you're in dev-mode.
5. Switch to the `dev-132` branch. I believe that's `git checkout dev-132` although I prefer GitHub Desktop over all the CLI commands.
6. Reload Atom, and then select `View` > `Developer` > `Open in Dev Mode` from the menu. Select your local `language-markdown` directory, although any other directory will do just fine.
7. Now play around with the dev-tools and your syntax-theme the way you already did.

**Comment by rkpatel33** [comment]
Thanks for the detailed instructions!

I have done all this, and I have done all this and am using this branch in
Atom now, but I am not sure what classes I am trying to grab to get whole
line per your screen shot. I was using this selector to do it before. I
read the `DisplayMarkerLayer` page but not sure how that translates to the
DOM.

```
    .code.fenced {
        background-color: #000000;

    }
```


_________________________
Rishi Patel | mail@rishinyc.com

On Tue, Sep 20, 2016 at 1:28 AM, David van Gemeren <notifications@github.com

**Comment by burodepeper** [comment]
Good question, forgot to mention that part. The bit of CSS you'll want is this:

```less
atom-text-editor,
:host {
  .line {
    &.embedded-code {
      background: fade(SOME_AWESOME_COLOR, 10%);
    }
  }
}

**Comment by rkpatel33** [comment]
I finally got this to work and it’s great! Is there a plan to incorporate
this into master at all?

The issue when I first tried it a few weeks back was that you need to use
`atom-text-editor::shadow` selector:

```
atom-text-editor::shadow,
:host {
  .line {
    &.embedded-code {
      background: fade(#000000, 40%);

      .fenced.code > .punctuation {
        color: gray;
      }

      .language.constant {
        color: gray;
      }
    }
  }
}
```

I need to do some more styling, but here’s what mine looks like now:




_________________________
Rishi Patel | mail@rishinyc.com

On Sat, Sep 24, 2016 at 4:23 AM, David van Gemeren <notifications@github.com

**Comment by burodepeper** [comment]
I think you forgot to post a picture ; )

> Is there a plan to incorporate this into master at all?

Yep, I think there's about a 90% chance this will go into `master`. Right now it is rather overzealous in creating the display markers, so it's not fit for distribution. I was waiting for a response from you before continuing. When it's stable enough, I intend to invite a few syntax-theme authors to pitch in. My 10% doubt is mostly precaution, and a little bit of doubt because I have no idea what the performance hit is on slower machines and/or in large documents. Especially since it's a feature that most users won't see unless their syntax-theme will support it, which it won't by default.

Potentially this feature would be more interesting as a separate package that also works for embedded Javascript and CSS in HTML documents, for instance. Of the top of my head I can't think of any other block-level embeds, but I'm sure there's some other use for it. Block-level comments perhaps, etc.

**Comment by rkpatel33** [comment]
Sorry about that, I pasted it directly in the email. Here is a link instead.

https://www.evernote.com/l/AAqRpCsznClNb5o5UqV_lOdZSZVKqpoMc3Y

I think I may be unclear on what you mean by “block-level embeds.” I often
embed code blocks of shell commands (image above), python, and even swift
code snippets. Not sure why languages should be limited as long as there is
an installed grammar for the language.

Ideally, I would love to create a theme for markdown files only, but not
sure that’s possible at a separate package. It would be along the lines of
this package for ST3:

https://github.com/SublimeText-Markdown/MarkdownEditing

So in my scenario, I would see the Cobalt 2 theme unless I am editing an MD
file, in which case it would switch to “Rishi’s-Markdown-Theme”. I suppose
in the end I could just extend Cobalt 2 as well. Now that I think about it
that seems to be the “Atomic” way.



_________________________
Rishi Patel | mail@rishinyc.com

On Tue, Oct 11, 2016 at 5:13 AM, David van Gemeren <notifications@github.com

**Comment by burodepeper** [comment]
Your screenshot looks good. I would personally give the gutter of the embedded blocks a different background too, but I'll leave the design up to you ; )

The "block-level embeds", well, you could say there are two types of elements: blocks and inlines. HTML is based on this. Blocks literally take up an entire block, for instance, a line from left to right, regardless of the amount of content on that line. An inline is part of a line, a single word, or a link for example. The whole difficulty with your original issue is that when Atom parses a document, it gets turned into a long list of inlines that can be styled. The bit of code I've written detects certain inlines, and then marks the blocks they're in so they can be styled separately. "Embedded code" on the other hand is not limited to Markdown. I think that's where the confusion comes from. This current fix targets "fenced code blocks" exclusively in Markdown document, but I think this behaviour is interesting to be used in other programming languages too. You could detect and mark comment blocks in a similar way as these fenced code blocks in Markdown. That is why I mentioned that this would be interesting as a stand-alone package.

A theme for Markdown files only doesn't have to be a separate package. For one, you can of course target Markdown elements, because they all reside in the `.text.md` scope; that is the parent scope/class of each line that contains Markdown code. This only allows you to target the afore mentioned inlines, not the body of the editor itself. You can target this however within the `atom-text-editor[data-grammar="text md"]` selector. You'll need to hack your syntax-theme or custom stylesheet a bit, but once you get the hang of it it's simpler than you though.

I'll try to fix the bug with my current solution for your issue this week, and then it can be part of the next release. I'll probably hide it under a new setting until I've verified that it isn't too big a hit on performance, and perhaps I'll even turn it into a separate package in the future.

**Comment by rkpatel33** [comment]
I see, that makes sense then. I think that would be a good idea, I’ve ever
seen that before in other editors.

Please let me know when it’s released and thanks for the pointer on
*atom-text-editor[data-grammar=“text
md”]*, I always forget about being able to do that.

I will pass on my theme when it’s in better shape as well.

Rishi


_________________________
Rishi Patel | mail@rishinyc.com

On Tue, Oct 11, 2016 at 3:45 PM, David van Gemeren <notifications@github.com

**Comment by burodepeper** [comment]
A little heads-up that this issue isn't dead yet. I've decided to develop this as a [separate package](https://github.com/burodepeper/mark-embedded-code), and to implement similar behavior for embedded code in HTML files as well. There's not much there yet, but I'll keep you posted when there's a first version available.

**Comment by rkpatel33** [comment]
Thanks for the heads up. Just watched the new project. I just read the new
blog post on getting rid of the shadow DOM in the new beta version. The new
version of Atom also seems like its improved performance considerably as
well.

Looking forward to seeing this develop. I wish I had more time right now to
help out but I’m deep into startup land so short on bandwidth.



_________________________
Rishi Patel | mail@rishinyc.com

**Comment by burodepeper** [comment]
This looks pretty cool, don't you think?

![schermafbeelding 2016-11-16 om 12 49 59](https://cloud.githubusercontent.com/assets/3703530/20346245/5a034564-abfb-11e6-9b36-7e26c69bb276.png)

Performance seems pretty good so far. Needs a bit more work before release, but you can give it a go by cloning the repo and linking it to your dev-mode via `apm link -d`.

**Comment by rkpatel33** [comment]
Looks great.  Will get very it a shot on my side. 

____________
Rishi K. Patel

On Nov 16, 2016, at 6:52 AM, David van Gemeren <notifications@github.com> wrote:

This looks pretty cool, don't you think?



Performance seems pretty good so far. Needs a bit more work before release, but you can give it a go by cloning the repo and linking it to your dev-mode via apm link -d.

**Comment by burodepeper** [comment]
Hey @rkpatel33,
Since Atom 1.13 is finally released, and after fixing a bug that erased all `.cursor-line` styling, I published a first version of the package, see: [mark-code-blocks](https://atom.io/packages/mark-code-blocks). I'm closing this issue and suggest we move any conversation to the package's repo. Let me know what you think.

**Comment by rkpatel33** [comment]
Hey, that sounds like to good idea. Great to see it in a separate repo.

Rishi


_________________________
Rishi Patel | mail@rishinyc.com
