### ISSUE TITLE
How can I add txt files?

### ISSUE THREAD

**Issue by orschiro** [burodepeper/language-markdown#133]
Dear @burodepeper,

Thank you very much for your package!

How can I add txt files to the supported file types?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18538826/5a02ad1c-7b12-11e6-8bdc-b5602d9c82be.png)

**Comment by burodepeper** [comment]
You're welcome.

Could you explain the reasoning behind your question?

There are already two mechanisms to trigger the markdown grammar. The first is to use a supported extension, such as `.md`. I mean, I wouldn't want to impose a grammar on anyone opening a `.txt` file and expecting plain-text. The second is to manually switch to the Markdown grammar. You can do that via the UI in the bottom right-hand corner (for a `.txt` file it will say `Plain Text`, click it and select `Markdown`), or via the keyboard shortcut (<kbd>ctrl + shift + L</kbd> on Mac OS X).

I'm not aware of a method via which you can directly extend the supported filetypes that a grammar supports. That setting is hardcoded as part of the grammar.

**Comment by orschiro** [comment]
Dear @burodepeper,

> The second is to manually switch to the Markdown grammar. You can do that via the UI in the bottom right-hand corner (for a .txt file it will say Plain Text, click it and select Markdown), or via the keyboard shortcut (ctrl + shift + L on Mac OS X).

This is a very useful hint and solves my problem differently, thank you!

I was asking because I use [Leanpub](http://leanpub.com/) to write a book. They write in Markdown but use `txt` files. 

As said, problem solved by switching with the shortcut. 

Thankfully,

-Robert

**Comment by burodepeper** [comment]
Let's make it even simpler! Let's make a custom key-combo which will switch to the Markdown grammar. For these directions I'm assuming that you're using Mac OS X, otherwise you might have to change a few not too difficult things. The idea is the same.

First open your custom keymaps via the Atom menu and select the option `Keymap...`. A file called `keymap.cson` will be opened in the current tab. Add the following to the bottom of this file:

```cson
'.editor':
  'cmd-alt-ctrl-m': 'select-markdown-grammar'
```

This tells the editor that if you press <kbd>cmd + alt + ctrl + M</kbd> that it has to execute the `select-markdown-grammar` command (which we'll create in a moment). Feel free to choose a keyboard shortcut of your own liking.

Now, via the Atom menu, select `Init Script...`, this will open a `init.coffee` file in the current tab. Paste the following code at the bottom of this file:

```coffee
atom.commands.add 'atom-text-editor', 'select-markdown-grammar': (event) ->
  editor = atom.workspace.getActiveTextEditor()
  grammar = editor.grammarRegistry.grammarForScopeName("text.md")
  editor.setGrammar(grammar)
```

This tells the editor to listen for the `select-markdown-grammar` command, and execute a bit of code if it's invoked. To finish it up, reload Atom (<kbd>cmd + alt + ctrl + L</kbd>) and try your new keyboard shortcut.

**Comment by burodepeper** [comment]
What are you writing a book about by the way?

**Comment by orschiro** [comment]
This is a great solution, thank you! :-)

My book is nothing special. A personal collection of short stories that I will probably call **Vocabulary of a Good Life**

-Robert

:-)

**Comment by burodepeper** [comment]
If you remember about it when you're done writing, I'd like to read it. Good luck!

**Comment by orschiro** [comment]
I will notify you!

Moreover, I think you can somehow follow the book if you want:

https://leanpub.com/vocabulary-for-a-good-life

Warmly,

-Robert
