### ISSUE TITLE
Bold across newline is not recognized as bold

### ISSUE THREAD

**Issue by joallard** [burodepeper/language-markdown#143]
```gherkin
Given the text 
  """
  this is some **bold
  text**
  """
When I render
Then "bold text" should be bold
# But it's not
```

Sorry to bother you with this @burodepeper, but do you think it can be fixed easily?

**Comment by burodepeper** [comment]
Nope, can't be easily fixed, unfortunately.

There has been a long discussion about this in `language-gfm` partly from which this package was developed. The big issue (as I see it) is that Atom parses content line by line, and in doing so doesn't give a multiline look ahead. My attempt to solve this resulted in an awful lot of false-positives, something that is at the core of what I try to prevent.

How I since see this issue is that inline styling elements (bold, italic, strike-through, etc.) are to be treated as inline elements, in other words: they don't span multiple lines by definition. This is somewhat parallel to how inline elements behave in HTML. This can be a bit confusing for a regular user, but the current parser in Atom simply doesn't allow for the most user friendly solutions.

The biggest culprit in trying to come up with a solid solution for supporting multiline inlines does also have to take into account that inlines can be nested. Throw those two together and you enter hell. If you want to try to fix it yourself I can give you some more technical details, but beware...

**Comment by joallard** [comment]
You're right, anyway I didn't have high expectations. I guess my only issue with this is parallel to #144, when a paragraph with eg. bold text gets a Reflow and breaks the style. Do you think we can easily prevent that from happening?

**Comment by burodepeper** [comment]
Okay, makes sense in your reflow example. Is there any particular reason why you're using manual reflow, and not use the editor soft-wrap-at-preferred-width option?

**Comment by joallard** [comment]
I guess that comes down more to personal preferences, but I prefer hard-wrapped text for better diffability.

**Comment by burodepeper** [comment]
To each his own. Anyway, I don't think I can help you with this issue any further at this moment. I'm hoping they'll use a different grammar parsing engine in 2.0.

**Comment by joallard** [comment]
@burodepeper I search but couldn't find: do you see that issue reported upstream?

**Comment by burodepeper** [comment]
> I search but couldn't find: do you see that issue reported upstream?

@joallard What are you referring to exactly?

**Comment by joallard** [comment]
> The big issue (as I see it) is that Atom parses content line by line, and in doing so doesn't give a multiline look ahead.

> This can be a bit confusing for a regular user, but the current parser in Atom simply doesn't allow for the most user friendly solutions.

I had the feeling this wasn't fixable in here, but does the parser give us the tools to do that?

**Comment by burodepeper** [comment]
Atom allows two types of matches with regards to grammars. There's a simple `match` (let's call these "inlines") which simply matches a pattern with one limitation: documents are parsed line-by-line, so you can't process anything multiline with these. The entire `match` has to occur on a single line. This feature is disabled by design in Atom. I spoke about it a long time ago with one of the core developers of Atom on Slack.

The other type has a `begin` and an `end` part, I call these "blocks". Both `begin` and `end` behave similar to `match`, however, the content between the two can contain line-breaks. The problem with these blocks is that the `end` part is optional; if it detects the `begin` part, it will still process anything that comes after as if it's part of that pattern. So when this involves emphasis, and you can't find the end part, your entire document might be marked emphasized. And it turns out that that happens quite often. With emphasis you have to account for nested emphasis, and then things get tricky because of these limitations. Have a look at [this discussion](https://github.com/atom/language-gfm/pull/89) which I believe is the reason I started developing this alternative.

I don't want to make it sound like you are the problem, but your hard-wrap preference doesn't play well with this kind of `begin` and `end` matching. And since the majority of users are no- or soft-wrappers, it happens that you are one of the few that's affected by this. So, yes, the tools are available, technically, but it's a problem that is not easily solved for all use-cases, and then sadly, the majority "wins". I chose to try and prevent false-positive, instead of the other way around.

You are more than welcome to give it a go yourself.

**Comment by joallard** [comment]
Right, thanks for the explainer. I'll keep the prevention of false positives in mind if I ever get around to it. I also wonder what the CMD spec says about a stray emphasis tag. Off the top, I'd say it shouldn't go across a markdown-block. (So `*` is either terminated with a `*` or `\n\n`) I'll also be sure to put some good test coverage if I do this, I'm pretty well acquainted with Rspec in the Ruby world.

**Comment by burodepeper** [comment]
> Off the top, I'd say it shouldn't go across a markdown-block. (So * is either terminated with a * or \n\n)

This is exactly one of the things that's impossible. The `match` alternative parses single lines, without a possibility of looking ahead or behind beyond that line. The `begin` alternative can _only_ be successfully terminated by an `end` match. You can't negate the begin-match.

This approach works good enough for programming languages, because proper grammar is absolute, and because the grammar rules are rather strict. An opening `(` needs a closing `)`. I have yet to come across any false-positive while programming.

> I'll also be sure to put some good test coverage if I do this

There are already a [bunch of tests](https://github.com/burodepeper/language-markdown/blob/master/spec/fixtures/inlines/emphasis.ass) in place, a good chunk of them disabled for these reasons.
