### ISSUE TITLE
git-diff info does not show when Markdown Grammar is selected

### ISSUE THREAD

**Issue by remidebette** [burodepeper/language-markdown#169]
Hi everyone

Firstly thank you for the awesome package which helps with the edition of static website content.

I would like to point out the following. Contrarily to other grammars, when Markdown is selected, the git-diff info does not display on the left of the code.

I might be unaware of some atom property that could be set to tackle with this? 
Or it might be a grammar issue (The display style is the same for language-gfm)

As you can see in this TOML screenshot, on the left, git-diff colors the changes since last commit:
(Notably, I added lines (green) and also modified sensitive content (yellow) to display it on this issue)
![toml](https://cloud.githubusercontent.com/assets/16523229/23575689/9f70add4-00d4-11e7-885a-f47cd7670e70.png)

Now for .md files, the git-diff info cannot be seen, even though "Move to Next Diff" command still works.
![markdown](https://cloud.githubusercontent.com/assets/16523229/23575706/013df3be-00d5-11e7-9660-fc5a0f85cf55.png)

Thanks again!

**Comment by burodepeper** [comment]
Hey @remidebette,

I don't think this is related directly to language-markdown. A clean install on my test machine shows no issues with git-diff. What I notice though, is that the line-numbers in your Markdown document are missing. Since both the line-numbers and git-diff markers are part of the gutter, perhaps you've disabled the gutter for Markdown files? At least, I think that's the direction you should be looking in. I have used Markdown-related packages before that disabled the gutter by default. I believe the typewriter package does that for instance.

I hope that helps.

**Comment by remidebette** [comment]
Hi @burodepeper,

Thank you for the fast answer, that was exactly the issue.
I also had installed typewriter and forgot it was there.

Thanks again!

**Comment by burodepeper** [comment]
You're welcome
