### ISSUE TITLE
Breaks highlighting on one-line display math

### ISSUE THREAD

**Issue by lierdakil** [burodepeper/language-markdown#171]
![image](https://cloud.githubusercontent.com/assets/7275622/23831608/1a9c9998-0736-11e7-88ca-04afc58f4eec.png)

**Comment by burodepeper** [comment]
Thanks for reporting.

I have replicated the issue, but it is actually because this syntax is not supported (yet). It should be quite trivial to add this, but could you tell me how common this syntax is? Is there a specific Markdown flavor that uses `$$` as a delimiter for inline math? I prefer to have a (verified) source before adding syntax variations.

Note: currently, inline math uses a single `$` as delimiter, and math blocks use `$$`.

**Comment by lierdakil** [comment]
It's not inline. It's still display (block) math, just written on one line. Pandoc supports this, for instance, as does, I believe, markdown-it-math.

**Comment by lierdakil** [comment]
Relaxing block math patterns from `/^\$\$$/` to `$$` should do it, however I'm not sure if there won't be any negative implications as a result.

**Comment by burodepeper** [comment]
Yeah, it is a trivial fix.

The downside is that Atom doesn't allow me to break out of a block match once it has started, even if it does not have an ending delimiter. This has resulted in quite a few issues before. It is why I prefer inline patterns over block patterns. Anyway, changing this shouldn't break any tests, so I see no immediate reason why not to add it. Can't promise that it will stay in "forever" though. If some conflicting issue is reported, I'll have to revisit this issue.

You can expect the fix for this to appear in the next update, maybe even today. For now, switching to the multiline syntax would be best:

```
$$
math stuff, woohoo
$$
```

**Comment by lierdakil** [comment]
Well, switching's not an option, but I relaxed patterns manually for now.

Here's an idea though: add `/^\s*$/` to end pattern. Most Markdown parsers I'm familiar with don't play well with paragraph breaks inside display math anyway. Since Atom doesn't support multiline lookaheads, breaking out of math block on empty line could be as good a solution as any.

**Comment by burodepeper** [comment]
I'll consider your alternative solution when I have a little more time. I'll relax the end pattern in the next update.

**Comment by burodepeper** [comment]
I published v0.20.0 with this fix.
