### ISSUE TITLE
Bash code highlighting makes all following text marked as string when if section is not closed

### ISSUE THREAD

**Issue by selivan** [burodepeper/language-markdown#175]
Example:

    ```bash
    if smth
    ...
    # no filnal fi
    ```
    
    All text following this lines will be highlighted as one big string.

Sometimes bash highlighting can be used to highlight non-bash code blocks for languages without native highlight support, for example rsyslog configs.

**Comment by burodepeper** [comment]
Thanks for reporting. As you point out in your example, this bug happens when a code block isn't completed. The bash grammar (in this case) doesn't release the document back to the Markdown grammar, and as such, everything that follows will be interpreted as bash. It's been a long standing issue, and there has been some progress/discussion about it recently, but I can't find the thread I'm thinking of. A similar issue from the language-gfm package with some additional details: https://github.com/atom/language-gfm/issues/21

Solution (for now): do not have incomplete code blocks in fenced-code. It isn't a real solution, but until the underlying issue isn't fixed, I can't really do anything about it.

**Comment by selivan** [comment]
What is upstream project that causes this issue? Atom edit itself?

**Comment by burodepeper** [comment]
https://github.com/atom/first-mate/issues/83

**Comment by selivan** [comment]
Voted it up, but seems it's stuck :(

**Comment by burodepeper** [comment]
I know. Anyway, I don't really see the point in keeping this open. If there's ever a solution, I'll go through the closed issues and ping you.
