### ISSUE TITLE
< in code block breaks syntax highlighting?

### ISSUE THREAD

**Issue by jxchong** [burodepeper/language-markdown#178]
I tested with both the tomorrow night dark syntax highlighting theme and minimal-dark and get the same results.

The following line indented by 4 spaces (should be a code block) seems to break syntax highlighting

    test1235 test<4 mydata.vcf.gz

For me, when I use Base16 Tomorrow Night dark, that means anything after the '<' will be red or orange instead of white.

It's ok if I add an extra space after the '<'

        test1235 test< 4 mydata.vcf.gz

**Comment by burodepeper** [comment]
Code blocks that start with 4 spaces aren't supported. The reason for that is that there's no way --within the way that Atom parses grammar-- to tell Atom that two consecutive lines are part of the same code block. If you wrap the code block in three backticks, your example doesn't present any problems, like this:

    ```
    test1235 test<4 mydata.vcf.gz
    ```

An additional feature of these fenced code blocks is that they allow you to specify the language of the code block, so the syntax highlighting is loaded for that language inside the code block. For example:

    ``` js
    const test = 0xff67 << 4 && mydata().getVCF('gz')
    ```

I hope that's enough to convince you to use fenced code blocks instead of indented ones. ;)

**Comment by jxchong** [comment]
Ah thank you so much for the answer. I'm currently trying to switch from Textmate2 where there was no difference as far as I can tell.

Well, I can switch going forward but all my poor legacy files... *wince*

**Comment by burodepeper** [comment]
I believe the language-gfm package, which is converted from TextMate, doesn't support it either. I'm not entirely sure though, but you could give that a try. If you're comfortable with some scripting, it shouldn't be too difficult to convert all your legacy files to use this new syntax.

**Comment by MarcinKonowalczyk** [comment]
I found that `lorem <- ipsum` is having some issues too (while both `lorem < ipsum` and `lorem - ipsum` work). I thought I'll post here as opposed to opening a new issue.

**Comment by burodepeper** [comment]
@MarcinKonowalczyk Could you post the exact code that I would need to replicate your issue?

**Comment by MarcinKonowalczyk** [comment]
😃 That was quick! I was just making a thing thinking I'll edit my previous post. Here is a screenshot from my editor:

![language-markdown-issue-18](https://user-images.githubusercontent.com/24707398/27585830-ad1e4340-5b35-11e7-8bf4-c265e7eb67bf.png)

The other installed packages are:
 - highlight-selected
 - markdown-themable-pdf
 - minimap
 - minimap-highlight-selected
 - pdf-view

so I don't think it's an interaction with some other markdown grammar definition.

**Comment by burodepeper** [comment]
Verified it, and it is actually the included/injected language-html package that's causing this. If you don't use html, feel free to disable that package for a quick fix. I haven't had time yet to look what exactly causes this. You would expect an incomplete tag not to be recognized.

**Comment by ackman678** [comment]
Just to clarify for others that there are two separate issues being discussed in this open thread:  

1. Parsing blocks of lines grouped by leading whitespace is not supported/possible in atom. Thus parsing indented 4 space code blocks as with original markdown doesn't work.

2. If the language-html package is enabled, lines containing a `<` character *followed immediately by a non-whitespace character* will break syntax highlighting for remaining characters on that line or until the end of file if using Markdown grammar. Whether syntax broken for just one line or rest of lines depends on whether the `<.` sequence occurs on a line already specially demarcated by Markdown syntax (title, list, quote) or a normal text line and whether there happens to be a `>` elsewhere to close the mistaken html tag. The exception is if `<.` occurs inside a fenced code block– then all is well.

<figure>
<img width="404" alt="screen shot 2018-08-06 at 2 40 54 pm" src="https://user-images.githubusercontent.com/4317308/43745523-103a5d0e-9994-11e8-8599-6bf5b3834cb0.png">
<img width="367" alt="screen shot 2018-08-06 at 2 41 14 pm" src="https://user-images.githubusercontent.com/4317308/43745524-105116c0-9994-11e8-8916-7b4d4fd4adff.png">
<img width="378" alt="screen shot 2018-08-06 at 2 42 21 pm" src="https://user-images.githubusercontent.com/4317308/43745525-1065b1a2-9994-11e8-870c-c94d576b29e2.png">
</figure>

**Comment by kylebarron** [comment]
It appears that `<-` is [_never_ valid HTML](https://www.w3.org/TR/html/syntax.html#tag-name). 

> 1. The first character of a start tag must be a U+003C LESS-THAN SIGN character (<).
> 2. The next few characters of a start tag must be the element’s tag name.

> Tags contain a tag name, giving the element’s name. HTML elements all have names that only use alphanumeric ASCII characters.

It then [defines "alphanumeric ASCII characters"](https://www.w3.org/TR/html/infrastructure.html#alphanumeric-ascii-characters) as `[a-zA-Z0-9]`.

I think it would be fine to scope `<-` specifically as markdown text, so that it doesn't get passed to language-HTML. More generally, it appears that all the rules in the language-html grammar are tags of the form `< ... >`, so I think it would be fine to only pass Markdown text to language-HTML for tokens starting with `<(?=[a-zA-z0-9\\!])`.

**Comment by burodepeper** [comment]
I think the only way to "really" solve this, is to add some barebones html matching to language-markdown, instead of inserting language-html. Markdown probably can do without all the fancy edge-cases that language-html might include.

**Comment by burodepeper** [comment]
Fixed/patched with a little help from @kylebarron. Will be available in next update. See b1a1da1 for more details.
