### ISSUE TITLE
Tutorial for running R Markdown

### ISSUE THREAD

**Issue by jailsonfm** [burodepeper/language-markdown#179]
Hey guys, sorry for posting this simple question, but I am for days trying to use `R Markdown` with `language-markdown` but without success. Unfortunately, I have navigated through the web to find some helpful info, but nothing found. My question is: how to compile the `.Rmd` as pdf or HTML. I RStudio everything goes nice, but I actually like to use Atom.
Any ideas, support, and suggestions are very welcomed!

**Comment by burodepeper** [comment]
Hey hello, I've never used R Markdown myself, but isn't it an option to use both Atom as well as RStudio? If you have a file open at the same time in both applications, I assume that it will reload the file in RStudio everything you save it in Atom, and also the other way around.

@4Oranges, @jtth: Do any of you have any ideas on this issue? I gathered your usernames from other issues involving R Markdown.

**Comment by jtth** [comment]
I use it, but mostly for writing. The syntax highlight of the various
Rmarkdown modules right now leaves something to be desired, but because
RStudio doesn't have native spell checking (at least on MacOS) I do use
either Atom or Sublime to do the real meat of the writing of prose.
Whether or not RStudio will reload the code depends on your platform. On
MacOS it works just fine, going from either to the other. Save in one,
and when you refocus the other window the text will reload. It works
fine and is almost instant on a test file, takes a little longer on 3000-
5000 line dissertation :P
--
jordan


On Fri, May 26, 2017, at 04:32 PM, David van Gemeren wrote:
> Hey hello, I've never used R Markdown myself, but isn't it an option
> to use both Atom as well as RStudio? If you have a file open at the
> same time in both applications, I assume that it will reload the
> file in RStudio everything you save it in Atom, and also the other
> way around.> @4Oranges[1], @jtth[2]: Do any of you have any ideas on this issue? I
> gathered your usernames from other issues involving R Markdown.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 


Links:

  1. https://github.com/4oranges
  2. https://github.com/jtth
  3. https://github.com/burodepeper/language-markdown/issues/179#issuecomment-304381794
