### ISSUE TITLE
Fold by heading

### ISSUE THREAD

**Issue by lemongrassnginger** [burodepeper/language-markdown#194]
Folding by indentation seems to be supported but folding by section heading isn't? Is it possible to implement section folding using language grammars alone? 

![image](https://user-images.githubusercontent.com/12435157/31082947-27318d92-a788-11e7-88e8-4bd959fe1d93.png)

Header based folding would be super useful to me since I find it helps being able to 'zoom out' and have an outline view of a document. I know there are dedicated packages for viewing document outlines but being able to fold sections in the editor would be a little bonus reduction in friction :) 

I wouldn't know where to start but if somebody's able to point the way I'll happily lend a hand implementing

**Comment by burodepeper** [comment]
No Markdown-specific folding has been added to this package. The indentation folding is added by Atom by default, I believe.

I've never really looked into adding heading-folding to this package. As far as I know, folding is based primarily on indentation. A change in indentation seems to be what starts a possible fold. A pattern to detect the end of that fold can be added to the grammar (see https://github.com/atom/language-javascript/blob/70138ec06a9f82a8bc2a4e17a2b799b56a5ff6da/settings/language-javascript.cson#L4) for instance. Folding by headers in Markdown unfortunately can't use either of those queues, so it seems it will have to be added programmatically, which also suggests that it would fit better in a separate package.

I have had a package installed at some point that added folding by headers, but I wasn't able to quickly find it again. If you happen to find it, please let me know. Perhaps the functionality can easily be added to this package as well. Otherwise it deserves a place in the FAQ or README.

**Comment by lemongrassnginger** [comment]
thanks for your response @burodepeper , I'm not sure I understand the fold pattern (this is the first I've really delved into language grammars). Do you happen to know if there's any good intro to grammars in atom? It's a topic I'm interested in so will have a play. If I come across anything I'll update it here. I did come across a package for folding but it seemed to be deprecated :(

**Comment by Announcement** [comment]
lel i was about to request the same thing @lemongrassnginger

**Comment by lemongrassnginger** [comment]
started package [markdown-fold](https://atom.io/packages/markdown-fold)

**Comment by burodepeper** [comment]
@lemongrassnginger Cool, and kudos! If I'm correct, your package does not add folding to specific headings/sections, but rather folds on a specific level (current h1, or all) of headings/sections, correct?

**Comment by lemongrassnginger** [comment]
@burodepeper, i don't know of a way to add those folding marks next to the line numbers. So instead a command is used to fold sections. Currently, it just looks for all section headers and folds those. One version folds all h1 headers so you just see the top level outline, the other folds at all heading levels so you see a bit more detail. There's a lot more it probably should be able to do, such as folding the section the cursor is currently in etc but it's a basic solution I was looking for

**Comment by burodepeper** [comment]
@lemongrassnginger Sounds good! I'll give it a try.

**Comment by jchook** [comment]
[markdown-folding](https://atom.io/packages/markdown-folding) exists, but isn't any better than your solution @lemongrassnginger. However, I did find this [open Atom issue](https://atom.io/packages/markdown-folding) which seems to address the root of this problem.
