### ISSUE TITLE
Make fenced code pattern detection case insensitive.

### ISSUE THREAD

**Issue by NGaffney** [burodepeper/language-markdown#197]
Currently code block language detection expects everything to be lower case, can it be made case insensitive?

**Comment by burodepeper** [comment]
Sure it can, but I'm not entirely sure that's a good idea.

This package parses grammar, so you could argue that its purpose is to notify you of syntactic errors, right? For instance, when programming, `while` isn't the same as `While`, because the compiler makes a difference between the two. Markdown is a bit more flexible (usually), but it still depends on a parser to actually compile it into html.

Since there is no absolute consensus on these matters, I try to go by a solution that causes fewest _false-positives_. For instance, while it seems feasible that `Javascript` and even `JavaScript` might be accepted by any markdown parser as valid, `javaSCRIPT` would be wrong, right? On the other hand, `javascript` and `js` seem universally assumed to work.

While making the patterns case insensitive isn't a difficult change (I think), I don't think it's in the best interest of the common user.

**Comment by NGaffney** [comment]
Right, understood. Thanks for getting back to me.

Would you accept a PR adding some info on the supported languages to the readme (or FAQ)?

**Comment by burodepeper** [comment]
Sure! I think the FAQ would be the best place. If you could also add a note that adding/supporting extra languages is relatively trivial (for me), I mean, it usually means just adding a single line to a single file, I'll add a comment to make it easier for people to PR in these changes themselves.
