### ISSUE TITLE
Disable indent in front-matter

### ISSUE THREAD

**Issue by mikestopcontinues** [burodepeper/language-markdown#203]
Hey, and thanks for the sweet plugin!

Right now, front-matter is auto-indented. This shouldn't be so. (Or at the very least, it should be optional). I've looked all over for an indent-precedent, but found none. YAML doesn't require an indent, and no library I've seen even has examples with indented front-matter. 

So... what gives? ;)

**Comment by burodepeper** [comment]
Indentation is something that's handled by Atom itself, and rarely by packages themselves. I believe you can opt out of it for particular scopes. For YAML, I've included the language-yaml package, so that's probably where you want to start your search. If you don't have indentation in regular YAML files, but you still do in front-matter, I'll have a more in-depth look at your issue.

**Comment by mikestopcontinues** [comment]
Hey, thanks for the quick response!

I did some more testing, and the problem exists when EITHER `language-yaml` "Auto Indent" OR `language-markdown` "Auto Indent" is enabled.

That said, I'm inclined to think it's a `language-yaml` issue too, as if you start a strictly yaml doc with `---` the problem occurs.

I opened an issue here:

https://github.com/atom/language-yaml/issues/97

**Comment by burodepeper** [comment]
Since it is now and still open over at language-yaml, I'm closing this one here. If they pick it up again and it turns out to be an issue with language-markdown, please re-open/submit it obviously.
