### ISSUE TITLE
not working on Atom 1.27.1 x64 on Windows 10

### ISSUE THREAD

**Issue by garretwilson** [burodepeper/language-markdown#221]
This doesn't seem to be working on Atom 1.27.1 x64 on Windows 10. I bring up a `foo.md` file, and it's showing that the Markdown language is selected. There is no syntax highlighting, however. I've already tried uninstalling and re-installing `language-markdown`.

**Comment by burodepeper** [comment]
What syntax theme are you using?

**Comment by garretwilson** [comment]
Both my UI Theme and Syntax Theme are set to "Atom Light".

**Comment by burodepeper** [comment]
Yeah, it has poor support. See the [README](https://github.com/burodepeper/language-markdown#syntax-theme-support). There are some themes there with proper support. Give them a try, and if it still doesn't do anything then, please post a screenshot.

**Comment by garretwilson** [comment]
But I don't want to use other themes.

Why should my theme change what the syntax looks like? If `_foo_` makes something italics, why shouldn't it be italics in all themes? If `##foo` is bold because it's a header, why shouldn't it be bold in all themes?

I'm afraid a syntax highlighter that forces me to use a certain theme isn't really useful. Is there a syntax highlighter for Atom that doesn't essentially break Atom? (I consider forcing me to use another theme "breaking Atom", because if Atom shipped without the light theme I would consider it broken for me, and this is the same thing.) It's a shame Atom doesn't support such a common format.

**Comment by garretwilson** [comment]
I switched to the "One Light" theme, and syntax highlighting shows up!

So this is a theme issue. But I still don't realize why the theme should disable syntax highlighting altogether.

I'll try the "One Light" theme for a while and see if it will work for me. Thanks for the reply

**Comment by burodepeper** [comment]
> Why should my theme change what the syntax looks like? If _foo_ makes something italics, why shouldn't it be italics in all themes? If ##foo is bold because it's a header, why shouldn't it be bold in all themes?

Because that's not how themes work. Text in between underscores is _emphasized_ and headings need to visually stand out from paragraphs. Yet, that doesn't mean that they _have_ to be italicized or bold. This is not Word.

The theme doesn't disable the syntax highlighting, it just doesn't recognize the semantic elements that the grammar parses. Themes don't highlight every little bit of code either. Differs per theme. Markdown is a bit of an outcast, because it shares very little with your average programming language.

However, you can easily extend your theme. See [this](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) and [this](https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/). It might seem daunting, but it gets easier quite fast. You could even write a little script that switches syntax themes just for Markdown documents.

If this goes over your head, language-markdown probably isn't for you. The default language-gfm should work fine for you.

**Comment by garretwilson** [comment]
> The default language-gfm should work fine for you.

I actually installed language-markdown to try to get _any_ Markdown syntax highlighting. Are you saying that if I would merely have switched to "One Light" instead of "Atom Light", I would have got Markdown syntax built-in anyway?

**Comment by burodepeper** [comment]
Oh no, the default markdown packages don't have much support for Markdown. This package just opens up possibilities, though themes need some adapting to make use of them.
