### ISSUE TITLE
Syntax highlight not working

### ISSUE THREAD

**Issue by ETaSky** [burodepeper/language-markdown#236]
For some reason, the syntax highlight is not working correctly after I installed the language-markdown. It is the same for rmarkdown file or markdown file. Is there a setting I need to set?
Thanks!

Jincheng
<img width="850" alt="screen shot 2018-10-12 at 11 41 56 am" src="https://user-images.githubusercontent.com/11180480/46879416-039ba580-ce14-11e8-9073-4937f73bde80.png">

**Comment by burodepeper** [comment]
You have to manually select the grammar instead of the Github Flavored Markdown. In the bottom right-hand corner of your Atom window, there's an option for that. Or search for Markdown with the "Grammar Selector" command, <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> on Mac, or the PC alternative.
