### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by sbrl** [burodepeper/language-markdown#260]
The syntax highlighting from this package is broken. For example, if I do a header like this:

```
## An example header
```

....Then only `An example header` is getting highlighted, not the `## ` too. Similarly, if I do

```
<!--
This is a comment
-->
```
... Then only `This is a comment` gets styled, and not the `<!--` and `-->` - though interestingly the start and end blocks in this case get italicised, just not coloured.

In addition, I was shocked to learn that Atom does _not_ provide it's own syntax highlighting for Markdown and there are _no alternatives_ to this package - so this package is essential.

**Comment by burodepeper** [comment]
Thank you for reporting your issue.

Actually, what you've encountered is the fact that your syntax-theme doesn't work well together with this package. All scopes that you mentioned are actually recognized by this package. Your syntax-theme however doesn't apply any styling to them. You can ask the author of your theme to make the necessary changes, or you can do it yourself. Good luck!

**Comment by paul-grassl** [comment]
> The syntax highlighting from this package is broken. For example, if I do a header like this:
> 
> ```
> ## An example header
> ```
> 
> ....Then only `An example header` is getting highlighted, not the `## ` too. Similarly, if I do
> 
> ```
> 
> ```
> 
> ... Then only `This is a comment` gets styled, and not the `<!--` and `-->` - though interestingly the start and end blocks in this case get italicised, just not coloured.
> 
> In addition, I was shocked to learn that Atom does _not_ provide it's own syntax highlighting for Markdown and there are _no alternatives_ to this package - so this package is essential.

I'm having the same issue. Which theme are you using @sbrl ? I'm using One Light. Maybe we could ask the One Light author to implement what is necessary to support correct markdown highlighting?

@burodepeper It's weird that everything worked until recently. I'm using the One light theme and the language-markdown package since a while and so far the highlighting was fine...

**Comment by burodepeper** [comment]
I would actually advise to disable language-markdown and start using (the default) language-gfm again. This package is no longer (actively) maintained.

**Comment by paul-grassl** [comment]
ah okay, thanks for the info!

**Comment by sbrl** [comment]
@paul-grassl I'm using One Dark. That's really odd that the default theme isn't providing styling there - I am **sure** it was before.

**Comment by burodepeper** [comment]
It isn't that odd.

I made language-markdown, because I wanted to style things that weren't styled by the default language-gfm package. I had to 'invent' scopes for certain elements. Why the support in the default themes is so poorly, is partly due to the somewhat limited coverage of the default scopes – ie, scopes are based on things from the programming world, and markdown isn't really programming – but also partly due to my poor understanding of how things tied together in Atom.

**Comment by sbrl** [comment]
Ah, I see @burodepeper. The odd thing though that I''m trying to get at is that it's not just that package that now has issues - comments in Javascript don't highlight properly either - and there are many other examples I'm now seeing. I now think this has something to do with the latest version of Atom, rather than this package in particular.
