### ISSUE TITLE
Nested square-brackets in references are not properly detected

### ISSUE THREAD

**Issue by bobrocke** [burodepeper/language-markdown#40]
If a `[ ]` pair is used, but not part of a reference, it get's scope assigned incorrectly.

![2015-11-06 at 3 29 pm](https://cloud.githubusercontent.com/assets/2962426/11008016/c31f143e-849b-11e5-93a9-bbf36dbdbd04.jpg)

The first is scoped: `<span class="punctuation md">[</span>` while the second is un-scoped.

**Comment by burodepeper** [comment]
I haven't found a way yet (and I'm afraid it might not be possible with the way parsing works in Atom) to detect matching pairs of (any kind of) brackets without resorting to using `begin` and `end` matches, which result in a lot of false-positives, because the `end` part is optional. False-positives are something I prefer to avoid in general.

From a different perspective: are you actively using square-brackets in your texts for this purpose instead of parentheses, or is this just a random situation you happened upon?

**Comment by bobrocke** [comment]
I do use share brackets from time to time for punctuation where parentheses don't seem to fit.

I can imagine that nested brackets might be hard, but TextMate gets it right. I was under the impression that Atom and TextMate used similar parsing. No?

![2015-11-06 at 6 59 pm](https://cloud.githubusercontent.com/assets/2962426/11011676/ae3244a2-84b8-11e5-9a2e-a18aefc05c91.jpg)

**Comment by burodepeper** [comment]
Atom's grammar was originally imported from Textmate yes, but I'm rewriting it for reasons beyond the scope of this issue. You can see in the 'original' code that links/references aren't the most accessible part of the grammar: https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L759

I will look into this issue, but for now, I advise not to use square brackets where parentheses are technically (of course, we all have our personal preferences) just as good, since they (square brackets) have such diverse functionality in the various forms and flavors of Markdown.

**Comment by burodepeper** [comment]
Your second screenshot is from Textmate?

**Comment by bobrocke** [comment]
Yes.

**Comment by burodepeper** [comment]
Not to self: https://github.com/textmate/markdown.tmbundle/blob/master/Syntaxes/Markdown.tmLanguage#L727

**Comment by burodepeper** [comment]
Quick update:
![schermafbeelding 2015-11-13 om 09 24 52](https://cloud.githubusercontent.com/assets/3703530/11141734/6dfd69b8-89e8-11e5-89f7-9e8c6715035d.png)

**Comment by bobrocke** [comment]
Looking good!

Here's maybe one more nested square-brackets special case that TextMate gets "right."

Atom:
![atom](https://cloud.githubusercontent.com/assets/2962426/11164603/4f77d8c6-8ac3-11e5-8be7-87c8f541bb1d.jpg)

TextMate:
![textmate](https://cloud.githubusercontent.com/assets/2962426/11164611/6b1616ba-8ac3-11e5-8bef-80fdb72a1278.jpg)

But the TextMate syntax grammar doesn't know about Markdown Extra!

**Comment by burodepeper** [comment]
Thanks for checking. I'll have a look at it.

**Comment by bobrocke** [comment]
No problem! I am liking this grammar better and better!

**Comment by burodepeper** [comment]
Hey @bobrocke, linked-images with special-attributes should now work in the latest update. As a bonus, I've also added a bit of code that automatically adds new list-items when working with lists. Let me know what you think!

**Comment by bobrocke** [comment]
It's working well for me!

**Comment by burodepeper** [comment]
Good to hear. I'm closing this issue. Let me know if you run into any other issues. I hope I've been able to steal you away from Textmate ; )
