### ISSUE TITLE
Improperly scoped `&`

### ISSUE THREAD

**Issue by bobrocke** [burodepeper/language-markdown#42]
In the screenshot below, the `&` in `Black & White` is being scoped as `<span class="invalid illegal bad-ampersand html">&amp;</span>` and should not be.

![2015-11-15 at 5 12 pm](https://cloud.githubusercontent.com/assets/2962426/11171356/094b9ff0-8bbc-11e5-9b62-4f34f2057617.jpg)

**Comment by burodepeper** [comment]
That actually is an invalid ampersand. Well, it's a grey area that is up for discussion anyway.




To support inline html, I am "lazily" including the language-html package as part of markdown, and in html a single ampersand in text is indeed invalid.




Now, the part where it gets weird is that if I were to decide to not include language-html but write my own implementation, I'd have to decide whether or not to implement that bit. However, I believe it should.




I'm on my phone now, but I can look up the docs later for you. CommonMark specifies a section on entities, of which the ampersand is one.




Since I assume your document will be converted to html, and a single ampersand in that context is indeed an invalid character, I believe in this case you should use the entity ampersand which is `&amp;`, because I don't think you can rely on your markdown parser to take care of properly formatting your inline html for you.




I could make the inline html optional via a settings option, but again, commonmark suggests it as an integral part of markdown.




What's your idea on the shade of gray we're in here?

**Comment by bobrocke** [comment]
You make a good argument. While using a `&` in common text is not unheard of, it probably isn't proper.

I'd say to leave it as it is.

**Comment by burodepeper** [comment]
Wow, replying from your phone really adds a lot of unnecessary whitespace...

Anyway, I agree with you that in regular text, an ampersand is not all that uncommon. My target audience is probably savvy enough to not make a big deal out of it, but I'm keeping it in my mind. I've planned to add some form of markdown linting to the package, which at least could inform a user why the ampersand is highlighted as invalid. Seems kind of a harsh treatment for the visually most delicate character of the ascii-set to be the metaphorical outcast.

Thanks for your input nonetheless.

**Comment by joallard** [comment]
While I appreciate the reflection, I'd have to respectfully disagree.

First, I tried inputing the `&` at different points in the [dingus](http://spec.commonmark.org/dingus/) and looking at both the HTML and the AST. Unless it is being recognized as a valid "ampersand-combination" (~~I forget the correct name~~ entity), `&` will be interpreted to mean the rendered character `&`, implemented as `&amp;` in HTML. In other words, the dingus will render `&` as `&amp;`. This also seems to be concordant with the CommonMark spec at [section 6.2 Entity and numeric character references](http://spec.commonmark.org/0.26/#entity-and-numeric-character-references). Examples [304](http://spec.commonmark.org/0.26/#example-304) and 305 seem to be particularly clear in our case.

But let's even forget about the spec for the moment. What does the user expect? Is it reasonable to expect the user to type out `&amp;` for every time they want to write an ampersand? In my opinion, not really. The job of the user should be as simple as possible and feasible, we shouldn't make them type `amp;` each time, just on the off-chance that it turns out to be an HTML entity.

Now I understand it might be an implementation challenge (or rather, hassle) to recognize every valid HTML entity (even though [the list](https://html.spec.whatwg.org/entities.json) is readily available). If that's a problem, I think it'd be reasonable to just assume what matches regex `/\&[^;]{2,};/` is an HTML entity.

I also understand the practical considerations in reusing `language-html`, and that's all fine, but I wanted to speak to what the ideal behavior should be.

Thanks for this package, cheers!

**Comment by burodepeper** [comment]
I agree about the ideal behavior, on what a user expects, but the current issue stems from re-using `language-html`. It is (for now) as simple as that. However, a thought just occurred to me: I might be able to pre-detect the `&` before `language-html` does anything to it. I haven't checked to be 100% certain, but I'm already parsing for Markdown entities (see [here](https://github.com/burodepeper/language-markdown/blob/master/grammars/repositories/inlines/entities.cson)), so why not add a solitary ampersand to them to let it be ignored by whatever rules follow. I'm not sure if it will work, but I'll give it a try.

**Comment by burodepeper** [comment]
I've solved the singular ampersand. It is now scoped as `ampersand.md` which prevents it from being subsequently scoped by `language-html`. The change will be part of the next release.

**Comment by joallard** [comment]
Wow, if it works, that's really fantastic! Super quick turnaround, thanks!

**Comment by burodepeper** [comment]
You're problem, it was bothering me too, and sometimes a solution suddenly presents itself after revisiting it after _almost a year_. Glad that it's fixed now. Release is on its way.
