### ISSUE TITLE
Incorrect highlight for double asterisks in code block

### ISSUE THREAD

**Issue by filipesilva** [burodepeper/language-markdown#88]
Using double asterisks inside code blocks via indent incorrectly highlights the document. Escaping them doesn't work because the backslashes will show.
![markdown-asterisk](https://cloud.githubusercontent.com/assets/4172079/13008829/c1b2c342-d190-11e5-9b67-a645aca8ee0c.gif)

**Comment by burodepeper** [comment]
That is an interesting one for discussion...

I've decided at some point to ignore 4-space-indented code-blocks because it allows for a lot of false-positives. The way Atom allows grammar to be parsed doesn't really have context-awareness, meaning it's parsed on a line-by-line basis. And because 4-space-indentation is a valid thing in, for instance, nested lists, or multiple paragraphs inside of quotes, I disabled it.

It would be an interesting candidate as a setting (switched off by default), but I haven't figured out an acceptable way of enabling/disabling parts of the grammar yet.

Until then, I'd suggest using the fenced-code-block style (especially since it allows you to specify which language it is!), and thanks for reporting this!

**Comment by filipesilva** [comment]
Roger. I'll use fenced block style. 

I don't know if it was related, but the editor seemed to crash some two or three times when I was trying to write down the link below. It only stopped crashing when I *pasted* the link instead of writing it out.

**Comment by burodepeper** [comment]
You mean, Atom crashed when you manually typed `https://github.com/isaacs/node-glob`? If so, did it crash at exactly the same letter each time? This package does parse the link (as part of the link), so it could have caused the crash, but there numerous other packages that might interfere. I'm quite sure however that it is not related to the indented code issue. If you can be more specific in replicating the crash, I'll see what I can find.

**Comment by filipesilva** [comment]
Just checked, and it crashes *after*  writing `[node-glob](https://github.com/isaacs/node-glob)` and then typing a space and some letters. It actually looks like it crashes but seems to come back after some 30s.

I have quite a few packages on so yes, it could have been due to any of them.

**Comment by burodepeper** [comment]
The bug doesn't replicate for me, so there's a good chance that it's related to another package. If you want to pursue it, try disabling and re-enabling your packages one-by-one until it crashes, then you have some idea of where to fill the issue.

While trying to replicate it, I noticed something else: I have no trouble with the double asterisk. Perhaps you still are still using `language-gfm` ;) Could you check which package is used in the lower right hand corner of your window. It should say just `Markdown`. I should've noticed sooner, because `language-markdown` also does not implement multi-line emphasis (ie, the problem that is caused by the asterisks).

Let me know if that works, and if it also solves the crashing issue. There might be some limitations on syntax-highlighting due to #83 though. That is still a work in progress.

**Comment by filipesilva** [comment]
This is a very minor bug really, I don't think it's worth to spend much time in it.

I get `GitHub Markdown` as the grammar. I don't get the option for just `Markdown` in the grammar selector. Should I?

**Comment by filipesilva** [comment]
Yeah I see I only have `language-gfm` in the installed packages. My bad man!

**Comment by burodepeper** [comment]
Haha, no problem! : )
More importantly, does it solve both problems?

**Comment by filipesilva** [comment]
It completely solves the first, but I still get chrome hanging for a bit so that tells me it's some other package. Cheers!

**Comment by burodepeper** [comment]
Try disabling `language-hyperlink` (it's one of the defaults though)

**Comment by burodepeper** [comment]
And you're welcome; happy to have helped!

**Comment by filipesilva** [comment]
Disabling `language-hyperlink` doesn't seem to help, but it's nothing important really. Much happier to have found a better markdown highlighter!

**Comment by burodepeper** [comment]
Enjoy!
